(()=>{
  'use strict';
  const CFG={storage:'marryWannaOfflineLicense',seed:'marryWannaMachineSeed',product:'marrywanna-b300',kid:'marrywanna-demo-2026-01',publicJwk:{kty:'OKP',crv:'Ed25519',x:'11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo',ext:true,key_ops:['verify']},required:'marrywanna_core',portal:'license-portal.html'};
  const state={valid:false,code:'ERR_LICENSE_MISSING',message:'Import a valid license file to unlock MarryWanna.',document:null,machineId:''};
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
  const b64url=bytes=>{let s='';new Uint8Array(bytes).forEach(b=>s+=String.fromCharCode(b));return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/g,'')};
  const from64=s=>{const p=String(s).replaceAll('-','+').replaceAll('_','/');const raw=atob(p+'='.repeat((4-p.length%4)%4));return Uint8Array.from(raw,c=>c.charCodeAt(0))};
  const error=(code,msg)=>{const e=new Error(msg);e.code=code;return e};
  async function machineId(){let seed=localStorage.getItem(CFG.seed);if(!seed){seed=b64url(crypto.getRandomValues(new Uint8Array(24)));localStorage.setItem(CFG.seed,seed)}const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`MARRYWANNA-B300|MID1|WEB|${seed}`));const token=b64url(digest).replace(/[^A-Za-z0-9]/g,'').toUpperCase().slice(0,24);state.machineId=`MID1-WEB-${token.slice(0,8)}-${token.slice(8,16)}-${token.slice(16,24)}`;return state.machineId}
  async function validate(doc){if(!doc||typeof doc!=='object')throw error('ERR_LICENSE_PARSE','License file could not be read.');if(doc.format!=='offline-license-v1'||!doc.payload||Number(doc.payload.schema_version)!==1)throw error('ERR_LICENSE_SCHEMA','Unsupported license format.');if(doc.alg!=='Ed25519'||doc.kid!==CFG.kid)throw error('ERR_KEY_UNKNOWN','The signing key is not trusted.');if(!doc.signature)throw error('ERR_SIGNATURE_INVALID','The license signature is missing.');let ok=false;try{const key=await crypto.subtle.importKey('jwk',CFG.publicJwk,{name:'Ed25519'},false,['verify']);ok=await crypto.subtle.verify({name:'Ed25519'},key,from64(doc.signature),new TextEncoder().encode(canonical(doc.payload)))}catch(_){throw error('ERR_SIGNATURE_INVALID','The license signature could not be verified.')}if(!ok)throw error('ERR_SIGNATURE_INVALID','The license signature is invalid.');const p=doc.payload;if(p.product_id!==CFG.product)throw error('ERR_PRODUCT_MISMATCH','This license is for a different product.');if(p.machine_id!==state.machineId)throw error('ERR_MACHINE_MISMATCH','This license belongs to a different Machine ID.');if(!Array.isArray(p.features)||!p.features.includes(CFG.required))throw error('ERR_FEATURE_REQUIRED','The core MarryWanna entitlement is missing.');const start=Date.parse(p.not_before),end=Date.parse(p.expires_at),now=Date.now();if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw error('ERR_LICENSE_SCHEMA','License validity dates are invalid.');if(now<start)throw error('ERR_LICENSE_NOT_YET_VALID','This license is not active yet.');if(now>end)throw error('ERR_LICENSE_EXPIRED','This license has expired.');return doc}
  function feature(name){return !!(state.valid&&state.document?.payload?.features?.includes(name))}
  function workspaceFeature(){const s=(()=>{try{return JSON.parse(sessionStorage.getItem('b300_auth_session')||'null')}catch(_){return null}})();return s?.workspace==='v2'?'inventory_workspace':s?.workspace==='v1'?'compliance_workspace':null}
  function entitlementCheck(){const block=$('entitlementBlock'),title=$('entitlementTitle'),copy=$('entitlementCopy');if(!block)return;const need=workspaceFeature();const denied=state.valid&&need&&!feature(need);block.classList.toggle('license-hidden',!denied);if(denied){title.textContent='Workspace not included in this license';copy.textContent=`This signed license does not include ${need}. Ask an administrator to issue a license with the required entitlement.`}}
  function apply(valid,code,msg,doc=null){state.valid=valid;state.code=code;state.message=msg;state.document=doc;document.body.classList.toggle('license-locked',!valid);render();entitlementCheck();window.dispatchEvent(new CustomEvent('marrywanna-license-changed',{detail:{valid,features:doc?.payload?.features||[]}}))}
  function render(){const p=state.document?.payload,valid=state.valid,st=$('licenseStatus');if(st){st.classList.toggle('valid',valid);$('licenseStatusTitle').textContent=valid?'License active':'License required';$('licenseStatusMessage').textContent=valid?'MarryWanna is unlocked for the licensed features.':state.message;const code=$('licenseStatusCode');if(code){code.textContent=valid?'':state.code||'';code.classList.toggle('license-hidden',valid||!state.code)}$('licenseStatusIcon').textContent=valid?'✓':'🔒'}if($('licenseMachineId'))$('licenseMachineId').textContent=state.machineId||'Generating…';const details=$('licenseDetails');if(details)details.classList.toggle('license-hidden',!valid);if(valid&&p){$('licenseCustomer').textContent=p.customer_name||p.customer_id||'—';$('licenseId').textContent=p.license_id||'—';$('licenseEdition').textContent=p.edition||'—';$('licenseValidFrom').textContent=new Date(p.not_before).toLocaleString();$('licenseValidUntil').textContent=new Date(p.expires_at).toLocaleString();$('licenseFeatures').innerHTML=(p.features||[]).map(x=>`<span class="license-chip">${esc(x)}</span>`).join('')}const rm=$('removeLicenseButton');if(rm)rm.classList.toggle('license-hidden',!localStorage.getItem(CFG.storage))}
  function open(){closeProfile();$('licenseModal')?.classList.remove('license-hidden');render()}
  function close(){$('licenseModal')?.classList.add('license-hidden')}
  function toggleProfile(){const p=$('licenseProfile');if(p)p.classList.toggle('open')}
  function closeProfile(){$('licenseProfile')?.classList.remove('open')}
  async function copyMachine(){try{await navigator.clipboard.writeText(state.machineId);toast('Machine ID copied.')}catch(_){toast('Copy failed. Select the Machine ID manually.')}}
  function download(value,name,type='application/json'){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type});const url=URL.createObjectURL(blob);const a=Object.assign(document.createElement('a'),{href:url,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function exportRequest(){if(!state.machineId)return toast('Machine ID is not ready.');download({schema_version:1,request_id:`REQ-${crypto.randomUUID().replaceAll('-','').toUpperCase()}`,machine_id:state.machineId,platform:'web',app_product:CFG.product,app_version:'1.0.0',fingerprint_version:1,generated_at:new Date().toISOString(),nonce:b64url(crypto.getRandomValues(new Uint8Array(12)))},'marrywanna-machine-request.json');toast('Machine request exported.')}
  async function activateFile(file){if(!file)return;try{const doc=JSON.parse(await file.text());await validate(doc);localStorage.setItem(CFG.storage,JSON.stringify(doc));apply(true,null,'License active.',doc);close();toast('License activated successfully.')}catch(err){if(!state.valid)apply(false,err.code||'ERR_LICENSE_PARSE',err.message);else{state.code=err.code;state.message=err.message;render()}toast(`${err.code||'ERR_LICENSE_PARSE'}: ${err.message}`)}}
  async function importFile(e){const input=e.target,file=input.files?.[0];await activateFile(file);input.value=''}
  function remove(){if(!localStorage.getItem(CFG.storage))return;if(!confirm('Remove this license from this device? MarryWanna will lock, but B300 business data and the Machine ID will be kept.'))return;localStorage.removeItem(CFG.storage);apply(false,'ERR_LICENSE_MISSING','Import a valid license file to unlock MarryWanna.');open();toast('License removed. MarryWanna is now locked.')}
  function toast(msg){let t=$('licenseToast');if(!t){t=document.createElement('div');t.id='licenseToast';Object.assign(t.style,{position:'fixed',right:'16px',bottom:'16px',zIndex:200,background:'#0f172a',color:'#fff',padding:'11px 14px',borderRadius:'10px',fontWeight:'700',fontSize:'13px',boxShadow:'0 12px 30px rgba(15,23,42,.25)'});document.body.appendChild(t)}t.textContent=msg;t.style.display='block';clearTimeout(t._timer);t._timer=setTimeout(()=>t.style.display='none',2600)}
  function setupDropzone(){const z=$('licenseDropzone');if(!z)return;['dragenter','dragover'].forEach(name=>z.addEventListener(name,e=>{e.preventDefault();z.classList.add('dragover')}));['dragleave','drop'].forEach(name=>z.addEventListener(name,e=>{e.preventDefault();z.classList.remove('dragover')}));z.addEventListener('drop',e=>activateFile(e.dataTransfer?.files?.[0]))}
  async function init(){apply(false,'ERR_LICENSE_MISSING','Import a valid license file to unlock MarryWanna.');setupDropzone();try{await machineId()}catch(_){apply(false,'ERR_MACHINE_ID_UNAVAILABLE','A stable Machine ID could not be generated.');open();return}const raw=localStorage.getItem(CFG.storage);if(!raw){render();open();return}try{const doc=JSON.parse(raw);await validate(doc);apply(true,null,'License active.',doc)}catch(err){apply(false,err.code||'ERR_LICENSE_PARSE',err.message);open()}}
  document.addEventListener('click',e=>{const p=$('licenseProfile');if(p&&!p.contains(e.target))closeProfile()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeProfile();close()}});
  window.MarryLicense={init,open,close,toggleProfile,copyMachine,exportRequest,importFile,remove,feature,entitlementCheck,state,config:CFG};
})();