const STORAGE = {
  transactions:'b300_transactions',
  metadata:'b300_shared_batch_metadata',
  locations:'b300_settings_locations'
};
const PRODUCTS = {
  seeds:{label:'Viable Seeds',short:'Seeds',unit:'units',decimals:0,max:9999,actions:['receive','send','loss','grow','move','adjust']},
  vcp:{label:'Vegetative Plants',short:'VCP',unit:'units',decimals:0,max:9999,actions:['receive','send','loss','lab','clone','grow','move','adjust']},
  wcp:{label:'Whole Plants',short:'WCP',unit:'units',decimals:0,max:9999,actions:['receive','send','loss','lab','harvest','move','adjust']},
  fm:{label:'Dried/Fresh Flowering kg',short:'FM',unit:'kg',decimals:3,max:null,actions:['receive','send','loss','package','lab','mix','process','move','adjust']},
  nfm:{label:'Dried/Fresh Non-flowering kg',short:'NFM',unit:'kg',decimals:3,max:null,actions:['receive','send','loss','package','lab','mix','process','move','adjust']},
  pi:{label:'Pure Intermediates kg',short:'PI',unit:'kg',decimals:3,max:null,actions:['receive','send','loss','package','lab','mix','process','move','adjust']},
  extracts:{label:'Finished Extracts mg THC',short:'Extracts',unit:'mg THC',decimals:0,max:9999999,actions:['receive','send','loss','move','adjust']},
  edible:{label:'Finished Edible mg THC',short:'Edible',unit:'mg THC',decimals:0,max:9999999,actions:['receive','send','loss','move','adjust']},
  topicals:{label:'Finished Topicals mg THC',short:'Topicals',unit:'mg THC',decimals:0,max:9999999,actions:['receive','send','loss','move','adjust']}
};
const ACTIONS = {receive:'Receive shipment',send:'Send shipment',loss:'Loss & destroy',package:'Package',lab:'Lab',clone:'Clone',mix:'Mix',grow:'Grow',harvest:'Harvest',process:'Process',move:'Move',adjust:'Adjust'};
const CATEGORY = {receiveDomestic:'Quantity Received in Canada',receiveInternational:'Quantity Imported into Canada',sendDomestic:'Quantity Sold in Canada',sendInternational:'Quantity Exported Outside Canada',destroy:'Quantity Destroyed',loss:'Quantity Incurred as Drying or Processing Loss',package:'Quantity Packaged',lab:'Quantity Sent for Analysis',grow:'Quantity Taken for Further Processing or Planted',growToWcp:'Quantity Transferred to Whole Cannabis Plant',harvest:'Plant Harvested',production:'Total Production',further:'Quantity Taken for Further Processing or Planted',adjustment:'Manual Count Adjustment',move:'Non-B300 Movement'};
const LEGACY_TYPES={addition:'Additions to Inventory',reduction:'Reductions to Inventory',adjustment:'Adjustments',opening:'Opening Inventory Baseline',metadata:'Internal Transfer / Retention'};
const DEFAULT_LOCATIONS=['Vault A','Vault B','Grow Room 1','Grow Room 2','Dry Room','Processing Room','Lab Hold','Finished Goods'];
const nowIso=()=>new Date().toISOString();
const uid=(prefix)=>`${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.floor(Math.random()*1296).toString(36).padStart(2,'0').toUpperCase()}`;
const readJson=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw==null?fallback:JSON.parse(raw)}catch(_){return fallback}};
const productByLabel=(label)=>Object.entries(PRODUCTS).find(([,p])=>p.label===label)?.[0]||null;
const fmt=(qty,key)=>{const m=PRODUCTS[key]||{decimals:3};return Number(qty||0).toLocaleString('en-CA',{minimumFractionDigits:m.decimals,maximumFractionDigits:m.decimals})};
const esc=(s)=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const txBatchId=(tx)=>tx?.v2BatchId||tx?.batchId||tx?.earlyBatchId||tx?.lateBatchId||'';
const txProduct=(tx)=>tx?.product||productByLabel(tx?.productType)||null;
const txDelta=(tx)=>{const q=Number(tx?.quantity||0);if(!Number.isFinite(q))return 0;const type=tx?.type;if(type===LEGACY_TYPES.addition||type===LEGACY_TYPES.opening)return Math.abs(q);if(type===LEGACY_TYPES.reduction)return -Math.abs(q);if(type===LEGACY_TYPES.adjustment)return q;return 0};
const inferAction=(category,type)=>{if(category===CATEGORY.receiveDomestic||category===CATEGORY.receiveInternational)return'receive';if(category===CATEGORY.sendDomestic||category===CATEGORY.sendInternational)return'send';if(category===CATEGORY.destroy||category===CATEGORY.loss)return'loss';if(category===CATEGORY.package)return'package';if(category===CATEGORY.lab||category==='Lab Result Recorded')return'lab';if(category===CATEGORY.harvest)return'harvest';if(category===CATEGORY.adjustment)return'adjust';if(category===CATEGORY.move)return'move';if(category===CATEGORY.growToWcp)return'grow';if(category===CATEGORY.further)return'process';if(category===CATEGORY.production&&type===LEGACY_TYPES.addition)return'receive';return'legacy'};
const normalizeTx=(tx)=>{const product=txProduct(tx);const batchId=txBatchId(tx);return {...tx,action:tx.v2Action||inferAction(tx.category,tx.type),product,batchId,quantity:Number(tx.quantity||0),unit:PRODUCTS[product]?.unit||'',b300Category:tx.category||tx.b300Category||'',location:tx.location||'',linkedBatchIds:Array.isArray(tx.v2LinkedBatchIds)?tx.v2LinkedBatchIds:(Array.isArray(tx.linkedBatchIds)?tx.linkedBatchIds:(tx.linkedBatchId?[tx.linkedBatchId]:[]))}};
const loadMeta=()=>{const m=readJson(STORAGE.metadata,{sequence:0,batches:{}});return {sequence:Number(m?.sequence||0),batches:(m&&typeof m.batches==='object'&&m.batches)||{}}};
function loadState(){
  const rawTx=readJson(STORAGE.transactions,[]);const transactions=(Array.isArray(rawTx)?rawTx:[]).map(normalizeTx);const meta=loadMeta();const map=new Map();
  [...transactions].reverse().forEach(tx=>{const product=tx.product,id=tx.batchId;if(!product||!id||!PRODUCTS[product])return;const saved=meta.batches[id]||{};const b=map.get(id)||{id,product,qty:0,location:saved.location||tx.location||'Unassigned',status:saved.status||'Available',labStatus:saved.labStatus||(['seeds','extracts','edible','topicals'].includes(product)?'Not required':'Not sent'),createdAt:saved.createdAt||tx.timestamp||nowIso(),parents:saved.parents||[],notes:saved.notes||'',thcLevel:saved.thcLevel||'',labDocument:saved.labDocument||'',analyzedAt:saved.analyzedAt||''};b.qty=Number((b.qty+txDelta(tx)).toFixed(PRODUCTS[product].decimals));if(tx.location)b.location=tx.location;map.set(id,b)});
  Object.entries(meta.batches).forEach(([id,saved])=>{if(map.has(id)){Object.assign(map.get(id),saved,{id,qty:map.get(id).qty});}else if(saved.product&&PRODUCTS[saved.product])map.set(id,{id,qty:0,status:'Closed',labStatus:'Not sent',parents:[],notes:'',...saved});});
  map.forEach(b=>{if(b.qty<=1e-9){b.qty=0;if(b.status!=='In analysis'&&b.status!=='Analyzed'&&b.status!=='Packaged')b.status='Closed'}});
  const locations=readJson(STORAGE.locations,DEFAULT_LOCATIONS);return {sequence:meta.sequence,locations:Array.isArray(locations)&&locations.length?locations:[...DEFAULT_LOCATIONS],batches:[...map.values()],transactions};
}
function saveState(s){const batches={};(s.batches||[]).forEach(b=>{batches[b.id]={product:b.product,location:b.location,status:b.status,labStatus:b.labStatus,createdAt:b.createdAt,parents:b.parents||[],notes:b.notes||'',thcLevel:b.thcLevel||'',labDocument:b.labDocument||'',analyzedAt:b.analyzedAt||''}});localStorage.setItem(STORAGE.metadata,JSON.stringify({sequence:s.sequence||0,batches}));localStorage.setItem(STORAGE.locations,JSON.stringify(s.locations||DEFAULT_LOCATIONS));}
let state=loadState();
let ui={tab:'dashboard',product:null,batch:null,action:null,actionProduct:null,actionBatch:null,search:''};
function toast(msg){const old=document.querySelector('.toast');if(old)old.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
function totalForProduct(key){return state.batches.filter(b=>b.product===key&&b.qty>0).reduce((a,b)=>a+Number(b.qty||0),0)}
function activeBatches(key=null){return state.batches.filter(b=>(!key||b.product===key)&&b.qty>0&&b.status!=='Closed')}
function getBatch(id){return state.batches.find(b=>b.id===id)}
function nextBatchId(product){state.sequence=(state.sequence||0)+1;const stage=['seeds','vcp','wcp'].includes(product)?'EB':'LB';const d=new Date(),stamp=`${String(d.getFullYear()).slice(2)}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return `${stage}-${stamp}-${String(state.sequence).padStart(3,'0')}`}
function normalizeQty(v,key){const n=Number(v);if(!Number.isFinite(n)||n<0)throw new Error('Enter a valid non-negative quantity.');const meta=PRODUCTS[key];if(meta.decimals===0&&!Number.isInteger(n))throw new Error(`${meta.short} must use whole numbers.`);if(meta.max!=null&&n>meta.max)throw new Error(`${meta.short} cannot exceed ${meta.max.toLocaleString('en-CA')} ${meta.unit} per entry.`);return Number(n.toFixed(meta.decimals))}
function ensureAvailable(batch,qty){if(!batch)throw new Error('Select a valid batch.');if(qty<=0)throw new Error('Quantity must be greater than zero.');if(qty>Number(batch.qty)+1e-9)throw new Error(`Cannot deduct ${qty}; batch ${batch.id} only has ${fmt(batch.qty,batch.product)} ${PRODUCTS[batch.product].unit}.`)}
function addTx({action,type,product,batchId,quantity,b300Category,location,linked=[],note=''}){const legacyType=type==='Addition'?LEGACY_TYPES.addition:type==='Reduction'?LEGACY_TYPES.reduction:type==='Adjustment'?LEGACY_TYPES.adjustment:LEGACY_TYPES.metadata;const stage=['seeds','vcp','wcp'].includes(product)?'early':'late';const raw={id:`B300-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${Math.floor(Math.random()*1000000).toString().padStart(6,'0')}`,timestamp:nowIso(),user:'Inventory Specialist',status:'Locked',type:legacyType,category:b300Category,productType:PRODUCTS[product]?.label||product,quantity:Number(quantity||0).toFixed(3),location:location||'',description:note||'',linkedBatchId:linked?.[0]||'',v2Action:action,v2BatchId:batchId,v2LinkedBatchIds:linked||[],sourceWorkspace:'Batch Manager v2'};if(stage==='early')raw.earlyBatchId=batchId;else raw.lateBatchId=batchId;const all=readJson(STORAGE.transactions,[]);const next=[raw,...(Array.isArray(all)?all:[])];localStorage.setItem(STORAGE.transactions,JSON.stringify(next));state.transactions.unshift(normalizeTx(raw));return raw;}
function createBatch({product,qty,location,status='Available',labStatus='Not sent',parents=[],notes=''}){const id=nextBatchId(product);const b={id,product,qty:Number(qty),location,status,labStatus,createdAt:nowIso(),parents:[...parents],notes};state.batches.unshift(b);return b}
function closeIfEmpty(b){if(Number(b.qty)<=1e-9){b.qty=0;b.status='Closed'}}
function commit(msg){saveState(state);render();toast(msg)}
function actionAllowed(product,action){return PRODUCTS[product]?.actions.includes(action)}
function field(label,name,type='text',opts={}){const {value='',required=false,placeholder='',min='',max='',step='',options=null,full=false,help=''}=opts;let control;if(options){control=`<select name="${name}" ${required?'required':''}>${options.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(value)?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`}else if(type==='textarea'){control=`<textarea name="${name}" ${required?'required':''} placeholder="${esc(placeholder)}">${esc(value)}</textarea>`}else{control=`<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} placeholder="${esc(placeholder)}" ${min!==''?`min="${min}"`:''} ${max!==''?`max="${max}"`:''} ${step!==''?`step="${step}"`:''}/>`}return `<div class="field ${full?'full':''}"><label>${esc(label)}${required?' *':''}</label>${control}${help?`<small>${esc(help)}</small>`:''}</div>`}
function productOptions(){return Object.entries(PRODUCTS).map(([k,p])=>({value:k,label:p.short+(p.unit?` — ${p.unit}`:'')}))}
function locationOptions(){return state.locations.map(x=>({value:x,label:x}))}
function batchOptions(product,selected='',filter=()=>true){return [{value:'',label:'Select batch…'},...activeBatches(product).filter(filter).map(b=>({value:b.id,label:`${b.id} — ${fmt(b.qty,b.product)} ${PRODUCTS[b.product].unit} — ${b.location}`}))]}
