function actionFields(action,product,batchId){const p=PRODUCTS[product];const b=getBatch(batchId);const qtyStep=p?.decimals===0?'1':'0.001';const qtyHelp=p?`${p.unit}; ${p.decimals===0?'whole numbers':p.decimals+' decimals'}${p.max?`; max ${p.max.toLocaleString('en-CA')}`:''}.`:'';const batchSelect=(filter=()=>true)=>field('Batch','batchId','text',{required:true,value:batchId||'',options:batchOptions(product,batchId,filter),full:true});let html='';
 if(action==='receive') html+=field('Product type','product','text',{required:true,value:product,options:productOptions(product)})+field('Origin','scope','text',{required:true,options:[{value:'domestic',label:'Within Canada'},{value:'international',label:'International'}]})+field('Supplier','party','text',{required:true,placeholder:'Supplier name'})+field('Shipment reference','reference','text',{placeholder:'Shipment / document #'} )+field('Quantity','quantity','number',{required:true,min:0,step:qtyStep,help:qtyHelp})+field('Storage location','location','text',{required:true,value:state.locations[0],options:locationOptions()});
 if(action==='send') html+=batchSelect()+field('Destination','scope','text',{required:true,options:[{value:'domestic',label:'Within Canada'},{value:'international',label:'International'}]})+field('Buyer','party','text',{required:true})+field('Shipment reference','reference','text',{})+field('Quantity','quantity','number',{required:true,min:0,max:b?b.qty:'',step:qtyStep,help:b?`Available: ${fmt(b.qty,b.product)} ${p.unit}.`:qtyHelp});
 if(action==='loss') html+=batchSelect()+field('Mode','lossMode','text',{required:true,options:[{value:'loss',label:'Loss'},{value:'destroy',label:'Destroy'}]})+field('Quantity','quantity','number',{required:true,min:0,max:b?b.qty:'',step:qtyStep})+field('Reason','reason','text',{required:true,full:true})+field('Destruction method (if destroy)','method','text',{full:true});
 if(action==='package') html+=batchSelect()+field('Quantity to package','quantity','number',{required:true,min:0,max:b?b.qty:'',step:qtyStep,help:'Creates a packaged batch while preserving the same product quantity.'})+field('Packaged location','location','text',{required:true,value:'Finished Goods',options:locationOptions()});
 if(action==='lab') html+=field('Lab action','labMode','text',{required:true,options:[{value:'send',label:'Send for analysis'},{value:'record',label:'Record lab results'}]})+batchSelect(x=>true)+field('Sample % (send only)','percent','number',{min:0.001,max:100,step:'0.001',value:'1'})+field('THC % (record only)','thc','number',{min:0,max:100,step:'0.0001'})+field('Document / COA reference','document','text',{full:true});
 if(action==='clone') html+=batchSelect()+field('Clone quantity','quantity','number',{required:true,min:1,step:'1',help:'Creates a new VCP batch linked to the selected VCP batch.'})+field('Clone location','location','text',{required:true,value:'Grow Room 1',options:locationOptions()});
 if(action==='mix'){const rows=activeBatches(product).map(b=>`<div class="multi-row"><input type="checkbox" name="mix_${esc(b.id)}" value="1"><div><b>${esc(b.id)}</b><div class="tiny muted">${esc(b.location)} · available ${fmt(b.qty,b.product)} ${esc(p.unit)}</div></div><input class="input" type="number" name="qty_${esc(b.id)}" min="0" max="${b.qty}" step="${qtyStep}" value="${b.qty}"></div>`).join('');html+=`<div class="field full"><label>Select two or more source batches *</label><div class="multi">${rows||'<div class="empty">No eligible batches.</div>'}</div><small>Selected batch IDs are unique by design. Enter how much to consume from each batch.</small></div>`+field('Mixed batch location','location','text',{required:true,value:b?.location||state.locations[0],options:locationOptions()});}
 if(action==='grow') html+=batchSelect()+field('Quantity to grow / transfer','quantity','number',{required:true,min:0,max:b?b.qty:'',step:qtyStep})+field('New batch location','location','text',{required:true,value:product==='seeds'?'Grow Room 1':'Grow Room 2',options:locationOptions()});
 if(action==='harvest') html+=batchSelect()+field('Harvest output','outputProduct','text',{required:true,options:[{value:'fm',label:'Flowering material (FM)'},{value:'nfm',label:'Non-flowering material (NFM)'}]})+field('WCP units harvested','quantity','number',{required:true,min:1,max:b?b.qty:'',step:'1'})+field('Output weight (kg)','outputQty','number',{required:true,min:0,step:'0.001'})+field('Output location','location','text',{required:true,value:'Dry Room',options:locationOptions()});
 if(action==='process'){const outputOpts=product==='pi'?[{value:'extracts',label:'Finished Extracts'},{value:'edible',label:'Finished Edible'},{value:'topicals',label:'Finished Topicals'}]:[{value:'pi',label:'Pure Intermediates (PI)'}];html+=batchSelect(x=>product!=='pi'||x.labStatus==='Analyzed')+field('Output product','outputProduct','text',{required:true,options:outputOpts})+field('Input quantity','quantity','number',{required:true,min:0,max:b?b.qty:'',step:qtyStep})+field(product==='pi'?'Output THC quantity (mg)':'Output quantity (kg)','outputQty','number',{required:true,min:0,step:product==='pi'?'1':'0.001'})+field('Output location','location','text',{required:true,value:'Processing Room',options:locationOptions()});}
 if(action==='move') html+=batchSelect()+field('Current location','current','text',{value:b?.location||'',help:'Read-only reference shown from the current batch state.'})+field('Move to','location','text',{required:true,value:state.locations.find(x=>x!==b?.location)||state.locations[0],options:locationOptions()});
 if(action==='adjust') html+=batchSelect()+field('Adjustment (+ / -)','delta','number',{required:true,step:qtyStep,help:'Negative adjustments cannot reduce inventory below zero.'})+field('Reason','reason','textarea',{required:true,full:true});
 return html;
}
function openAction(action,product,batchId=null){if(product&&!actionAllowed(product,action)){toast(`${ACTIONS[action]} is not available for ${PRODUCTS[product].short}.`);return}ui.action=action;ui.actionProduct=product;ui.actionBatch=batchId;renderModal();}
function closeModal(){ui.action=null;document.getElementById('modalRoot')?.remove()}
function renderModal(){document.getElementById('modalRoot')?.remove();if(!ui.action)return;const wrap=document.createElement('div');wrap.id='modalRoot';const title=ACTIONS[ui.action];const product=ui.actionProduct||'seeds';wrap.innerHTML=`<div class="modal-bg"><div class="modal"><div class="modal-head"><div><h3>${esc(title)}</h3><p>Batch Manager v2 automatically writes the supporting ledger transaction(s).</p></div><button class="x" data-close>×</button></div><form id="actionForm"><div class="modal-body"><div class="alert info">V2 data is stored only under <b>b300_v2_*</b>. Legacy data is not read or modified.</div><div id="formError"></div><div class="formgrid" id="dynamicFields">${actionFields(ui.action,product,ui.actionBatch)}</div></div><div class="modal-foot"><button type="button" class="btn" data-close>Cancel</button><button type="submit" class="btn primary">Complete ${esc(title)}</button></div></form></div></div>`;document.body.appendChild(wrap);wrap.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);const form=wrap.querySelector('#actionForm');form.addEventListener('change',e=>{if(e.target.name==='product'){ui.actionProduct=e.target.value;wrap.querySelector('#dynamicFields').innerHTML=actionFields(ui.action,ui.actionProduct,null)}else if(e.target.name==='batchId'&&ui.action!=='mix'){ui.actionBatch=e.target.value;wrap.querySelector('#dynamicFields').innerHTML=actionFields(ui.action,ui.actionProduct,ui.actionBatch)}});form.onsubmit=e=>{e.preventDefault();try{executeAction(ui.action,new FormData(form));closeModal()}catch(err){wrap.querySelector('#formError').innerHTML=`<div class="alert error">${esc(err.message||String(err))}</div>`}}}
