// Generated assets are committed so branch-based GitHub Pages needs no build job.
const fs = require("node:fs");
const path = require("node:path");
const { execFileSync } = require("node:child_process");
const babel = require("@babel/core");
const root = path.resolve(__dirname, "..");
const vendor = path.join(root, "assets/vendor");
fs.mkdirSync(vendor, { recursive: true });
const sources = [
  [
    "react/umd/react.production.min.js",
    "react.production.min.js",
    "react/LICENSE",
  ],
  [
    "react-dom/umd/react-dom.production.min.js",
    "react-dom.production.min.js",
    "react-dom/LICENSE",
  ],
  ["lucide/dist/umd/lucide.js", "lucide.js", "lucide/LICENSE"],
  ["pdf-lib/dist/pdf-lib.min.js", "pdf-lib.min.js", "pdf-lib/LICENSE.md"],
];
for (const [source, name, license] of sources) {
  fs.copyFileSync(
    path.join(root, "node_modules", source),
    path.join(vendor, name),
  );
  fs.copyFileSync(
    path.join(root, "node_modules", license),
    path.join(vendor, name + ".LICENSE"),
  );
}
const transformed = babel.transformFileSync(
  path.join(root, "src/compliance.jsx"),
  {
    presets: [require.resolve("@babel/preset-react")],
    comments: false,
    compact: true,
  },
);
fs.writeFileSync(
  path.join(root, "assets/js/compliance.js"),
  "/* Generated by npm run build from src/compliance.jsx. */\n" +
    transformed.code +
    "\n",
);
execFileSync(
  process.execPath,
  [
    path.join(root, "node_modules/tailwindcss/lib/cli.js"),
    "-i",
    path.join(root, "src/compliance.css"),
    "-o",
    path.join(root, "assets/css/compliance.css"),
    "--minify",
    "--config",
    path.join(root, "tailwind.config.js"),
  ],
  { stdio: "inherit", cwd: root },
);
console.log("Static compliance assets built.");
